version: "3.8"
services:
  proxy:
      build: .
      image: nginx:latest
      container_name: proxy
      ports:
        - 80:8080
      networks:
        - net1
networks:
  net1:
    driver: bridge